CURL=curl -L

all: \
	cache/nix-2.0.4-x86_64-linux.tar.bz2 \
	cache/jdk-8u181-linux-x64.rpm \
	cache/netbeans-8.2-javase-linux.sh \
	cache/ideaIC-2018.2.2.tar.gz

cache/nix-2.0.4-x86_64-linux.tar.bz2: | cache
    ${CURL} https://nixos.org/releases/nix/nix-2.0.4/nix-2.0.4-x86_64-linux.tar.bz2 > $@

cache/jdk-8u181-linux-x64.rpm: | cache
	${CURL} -L --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
		"http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.rpm" > $@

cache/netbeans-8.2-javase-linux.sh: | cache
	${CURL} http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javase-linux.sh > $@

cache/ideaIC-2018.2.2.tar.gz: | cache
	${CURL} https://download.jetbrains.com/idea/ideaIC-2018.2.2.tar.gz > $@

cache:
	mkdir cache

.PHONY: all
