CURL=curl -L

all: \
	cache/nix-2.1.1-x86_64-linux.tar.bz2 \
	cache/jdk-8u172-linux-x64.rpm \
	cache/netbeans-8.2-javase-linux.sh \
	cache/ideaIC-2018.2.2.tar.gz \
	cache/CLion-2018.2.3.tar.gz

cache/nix-2.1.1-x86_64-linux.tar.bz2: | cache
	${CURL} 'https://nixos.org/releases/nix/nix-2.1.1/nix-2.1.1-x86_64-linux.tar.bz2' > $@


cache/jdk-8u172-linux-x64.rpm: | cache
	${CURL} -H "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
		'http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.rpm' > $@

cache/netbeans-8.2-javase-linux.sh: | cache
	${CURL} 'http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javase-linux.sh' > $@

cache/ideaIC-2018.2.2.tar.gz: | cache
	${CURL} 'https://download.jetbrains.com/idea/ideaIC-2018.2.2.tar.gz' > $@

cache/CLion-2018.2.3.tar.gz: | cache
	${CURL} 'https://download.jetbrains.com/cpp/CLion-2018.2.3.tar.gz' > $@

cache:
	mkdir cache

.PHONY: all
